// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXup2x4SdjhNF0JrD6N0OqTieJl_naO3I',
    appId: '1:822986424806:web:d39507a45a187c33bf5627',
    messagingSenderId: '822986424806',
    projectId: 'gothilo',
    authDomain: 'gothilo.firebaseapp.com',
    databaseURL: 'https://gothilo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothilo.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXup2x4SdjhNF0JrD6N0OqTieJl_naO3I',
    appId: '1:822986424806:android:d39507a45a187c33bf5627',
    messagingSenderId: '822986424806',
    projectId: 'gothilo',
    databaseURL: 'https://gothilo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothilo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXup2x4SdjhNF0JrD6N0OqTieJl_naO3I',
    appId: '1:822986424806:ios:d39507a45a187c33bf5627',
    messagingSenderId: '822986424806',
    projectId: 'gothilo',
    databaseURL: 'https://gothilo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothilo.firebasestorage.app',
    iosBundleId: 'com.gothilo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXup2x4SdjhNF0JrD6N0OqTieJl_naO3I',
    appId: '1:822986424806:macos:d39507a45a187c33bf5627',
    messagingSenderId: '822986424806',
    projectId: 'gothilo',
    databaseURL: 'https://gothilo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gothilo.firebasestorage.app',
    iosBundleId: 'com.gothilo',
  );
} 